[server]
# Maximum file upload size in MB (default is 200MB)
maxUploadSize = 1024
# Do not launch a browser when the app starts.
headless = true
# Reload when changes are made.
runOnSave = true

[browser]
# Turns off Streamlitâ€™s anonymous usage telemetry
gatherUsageStats = false
